version: '3.9'

services:

  broker:
    container_name: broker_ws
    image: broker_ws_img
    build: broker
    ports:
      - "9000:9000"
    expose:
      - "9000"
    depends_on:
      - auldfellas
      - girlpower
      - dodgydrivers

  auldfellas:
    container_name: auldfellas_ws
    image: auldfellas_ws_img
    build: auldfellas
    ports:
      - "9001:9001"

  girlpower:
    container_name: girlpower_ws
    image: girlpower_ws_img
    build: girlpower
    ports:
      - "9002:9002"

  dodgydrivers:
    container_name: dodgydrivers_ws
    image: dodgydrivers_ws_img
    build: dodgydrivers
    ports:
      - "9003:9003"
