version: '3.9'

services:

  broker:
    container_name: broker_ws
    image: broker_ws_img
    build: broker
    ports:
      - "9000:9000"

  auldfellas:
    container_name: auldfellas_ws
    image: auldfellas_ws_img
    build: auldfellas
    ports:
      - "9001:9001"
    depends_on:
      - broker

  girlpower:
    container_name: girlpower_ws
    image: girlpower_ws_img
    build: girlpower
    ports:
      - "9002:9002"
    depends_on:
      - broker

  dodgydrivers:
    container_name: dodgydrivers_ws
    image: dodgydrivers_ws_img
    build: dodgydrivers
    ports:
      - "9003:9003"
    depends_on:
      - broker

  client:
    container_name: client_ws
    image: client_ws_img
    build: client
    depends_on:
      - dodgydrivers
      - girlpower
      - auldfellas
      - broker
