version: '3'

services:

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq_lab4
    ports:
      - "8161:8161"
      - "61616:61616"

  auldfellas:
    image: auldfellas_jms_img
    container_name: auldfellas_jms
    build: auldfellas
    network_mode: "service:activemq"
    depends_on:
      - activemq

  girlpower:
    image: girlpower_jms_img
    container_name: girlpower_jms
    build: girlpower
    network_mode: "service:activemq"
    depends_on:
        - activemq

  dodgydrivers:
    image: dodgydrivers_jms_img
    container_name: dodgydrivers_jms
    build: dodgydrivers
    network_mode: "service:activemq"
    depends_on:
      - activemq

  broker:
    image: broker_jms_img
    container_name: broker_jms
    build: broker
    network_mode: "service:activemq"
    depends_on:
      - activemq

  client:
    image: client_jms_img
    container_name: client_jms
    build: client
    network_mode: "service:activemq"
    depends_on:
      - auldfellas
      - dodgydrivers
      - girlpower
      - broker
