version: '3'

services:

  broker:
    container_name: broker_akka
    image: broker_akka_img
    build: broker
    ports:
      - "2551:2551"
    
  auldfellas:
    container_name: auldfellas_akka
    image: auldfellas_akka_img
    build: auldfellas
    depends_on:
      - broker
    network_mode: "service:broker"


  girlpower:
    container_name: girlpower_akka
    image: girlpower_akka_img
    build: girlpower
    depends_on:
      - broker
    network_mode: "service:broker"


  dodgydrivers:
    container_name: dodgydrivers_akka
    image: dodgydrivers_akka_img
    build: dodgydrivers
    depends_on:
      - broker
    network_mode: "service:broker"

  client:
    container_name: client_akka
    image: client_akka_img
    build: client
    network_mode: "service:broker"
    depends_on:
      - broker
      - dodgydrivers
      - auldfellas
      - girlpower
